apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-gateway
  template:
    metadata:
      labels:
        app: frontend-gateway
    spec:
      containers:
      - name: gateway
        image: nginx:latest
        ports:
        - containerPort: 80